# Generated by Django 4.2.3 on 2023-09-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
